language: generic

matrix:
  include:
  - env: PROJECT=projects/web-ui/
    node_js: node
  - stage: Deploy
    script: echo DEPLOYING

before_script: echo $TRAVIS_COMMIT_RANGE
script: if .travis/project-has-new-commits.sh $TRAVIS_COMMIT_RANGE $PROJECT; then cd $PROJECT && ./.travis/ci.sh; else echo "NO CHANGES SINCE LAST COMMIT"; fi
