matrix:
  include:
  - env: PROJECT=projects/web-ui/
    language: node_js
    node_js: node
    cache: npm
    addons:
      chrome: stable
  - env: PROJECT=projects/infrastructure/
    language: generic
  - stage: Deploy production
    language: generic
    deploy:
      provider: script
      skip_cleanup: true
      script: bash projects/infrastructure/.travis/deploy.sh
      on:
        branch: master

before_script: echo $TRAVIS_COMMIT_RANGE
script: if .travis/project-has-new-commits.sh $TRAVIS_COMMIT_RANGE $PROJECT; then cd $PROJECT && ./.travis/ci.sh; else echo "NO CHANGES SINCE LAST COMMIT"; fi
